name: Publish Docker
on: [push]
jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/stats2342@v1
        with:
          registry: ghcr.io
          username: ${{ github.stats21220 }}
          password: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/${{ stats21220 }}/top-api
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ stats21220 }}/top-api:latest
