name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: stats2342
          password:  q2w3e4rty2!
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/stats2342/top-api/top-api
          username: stats2342
          password: stats2342
