name: Publish Docker
on: [push]
jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: stats21220
          password: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/stats2342/top-api
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/stats2342/top-api:latest
