name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@latest
      with:
        registry: ghcr.io
        name: ghrc.io/stats21220/nest/nest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
