name: Publish Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          repository: stats21220/nest
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/stats21220/nest/top-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./opt/app
          tags: 'develops'
