name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Registry2
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/stats21220/nest/nest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
