name: Publish Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to registry
        run: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: ghcr.io/stats21220/nest/top-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develops'
