name: Docker
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          registry: ghcr.io
          name: ghcr.io/stats21220/nest/top-api2
          username: stats2342
          password: q2w3e4rty2!
          tags: 'dev'
