name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/stats2342/top-api/top-api
          run: docker login -u “stats2342” -p “q2w3e4rty2!”
          username: stats2342
          password: q2w3e4rty2!
