name: Docker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: docker://ghcr.io/stats2342/nest
        with:
          registry: ghcr.io
          name: ghcr.io/stats21220/nest/nest
          username: stats2342
          password: q2w3e4rty2!
          tags: "develop"

